import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const toolDirectory = path.dirname(fileURLToPath(import.meta.url));
const root = path.dirname(toolDirectory);
const htmlPath = path.join(root, "ui", "index.html");
const outputPath = path.join(root, "ui", "vendor", "app.min.js");
const require = createRequire(import.meta.url);
const Babel = require(path.join(toolDirectory, "vendor", "babel-7.26.4.min.js"));

const html = await readFile(htmlPath, "utf8");
const match = html.match(
  /<script type="text\/x-adhikar-jsx" id="adhikar-ui-source">([\s\S]*?)<\/script>/,
);
if (!match) {
  throw new Error("Could not find the canonical Adhikar JSX source block.");
}

const source = match[1].trim();
const sourceHash = createHash("sha256").update(source).digest("hex");
const transformed = Babel.transform(source, {
  presets: ["react"],
  comments: false,
  compact: true,
  sourceMaps: false,
}).code;
const banner = `/* Generated by tools/build_ui.mjs; source-sha256=${sourceHash} */\n`;
await writeFile(outputPath, banner + transformed + "\n", "utf8");

// Cache-bust the bundle URL. /assets/* is served immutable with a 1-year max-age,
// and app.min.js keeps a stable filename, so returning browsers would otherwise
// never see a rebuild. Stamping the content hash as a query string gives each
// build a distinct URL while leaving the direct-GET response headers immutable.
const version = sourceHash.slice(0, 12);
const referencePattern = /(<script src="\/assets\/app\.min\.js)(?:\?v=[0-9a-f]+)?("><\/script>)/;
if (!referencePattern.test(html)) {
  throw new Error("Could not find the app.min.js script reference to version.");
}
const versionedHtml = html.replace(referencePattern, `$1?v=${version}$2`);
if (versionedHtml !== html) {
  await writeFile(htmlPath, versionedHtml, "utf8");
}
console.log(`Built ${path.relative(root, outputPath)} from source ${version}; bundle URL pinned to ?v=${version}.`);

